export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const FETCH_POST_COMMENTS_REQUEST = 'FETCH_POST_COMMENTS_REQUEST';

export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS';

export const FETCH_POST_COMMENTS_FAILURE = 'FETCH_POST_COMMENTS_FAILURE';

export const SET_CURRENT_POST = 'SET_CURRENT_POST';

export const FETCH_SUBREDDIT_POSTS_REQUEST = 'FETCH_SUBREDDIT_POSTS_REQUEST';

export const FETCH_SUBREDDIT_POSTS_SUCCESS = 'FETCH_SUBREDDIT_POSTS_SUCCESS';

export const FETCH_SUBREDDIT_POSTS_FAILURE = 'FETCH_SUBREDDIT_POSTS_FAILURE';

export const SET_CURRENT_SUBREDDIT = 'SET_CURRENT_SUBREDDIT';
